/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flightschedulersamatkinssja5408;

import static flightschedulersamatkinssja5408.FlightSchedulerSamAtkinssja5408.connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author samatkins
 */
public class Bookings {
    public Bookings(int flightId, int dayId, int customerId)
    {
        try 
        {
            if(!isTableExisting()) {
                createTable();
            }
            PreparedStatement insertQuery = connection.prepareStatement(
                    "INSERT INTO Bookings (flightId, dayId, customerId)"
                    + " VALUES (?, ?, ?)");
            insertQuery.setString(1, "" + flightId);
            insertQuery.setString(2, "" + dayId);
            insertQuery.setString(3, "" + customerId);
            insertQuery.executeUpdate();
        }
        catch (SQLException sqlException)
        {
            sqlException.printStackTrace();
        }
    }
    
    private void createTable() throws SQLException 
    {
        PreparedStatement create = connection.prepareStatement(
                "CREATE TABLE Bookings("
                        + "bookingId INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1), "
                        + "flightId INTEGER NOT NULL, "
                        + "dayId INTEGER NOT NULL, "
                        + "customerId INTEGER NOT NULL, "
                        + "PRIMARY KEY(bookingId))");
        create.execute();
    }
    
    private static boolean isTableExisting() 
    {
        
        try {
            PreparedStatement s = connection.prepareStatement(
                "SELECT * FROM Bookings");
            s.execute();
            return true;
      } catch (SQLException ex) {
            return false;
        }
    }
}
