/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flightschedulersamatkinssja5408;
import java.sql.*;
import static flightschedulersamatkinssja5408.FlightSchedulerSamAtkinssja5408.connection;
/**
 *
 * @author samatkins
 */
public class Day {
    private final int month;
    private final int year;
    private final int day;
    private final String date;
    private final int dayId;
    private static int numDays = 0;

    public Day(int year, int month, int day)
    {
        numDays++;
        this.day = day;
        this.month = month;
        this.year = year;
        date = "" + month + "/" + day + "/" + year;
        dayId = numDays;
        try 
        {
            if(!isTableExisting()) {
                createTable();
            }
            PreparedStatement insertQuery = connection.prepareStatement(
                    "INSERT INTO Days (date)"
                    + " VALUES (?)");
            insertQuery.setString(1, date);
            insertQuery.executeUpdate();
        }
        catch (SQLException sqlException)
        {
            sqlException.printStackTrace();
        }
    }
    
    private static boolean isTableExisting() 
    {
        try {
            PreparedStatement s = connection.prepareStatement(
                "SELECT * FROM Days");
            s.execute();
            return true;
      } catch (SQLException ex) {
            return false;
        }
    }
    
    private void createTable() throws SQLException 
    {
        PreparedStatement create = connection.prepareStatement(
                "CREATE TABLE Days("
                        + "dayId INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1), "
                        + "date LONG VARCHAR, "
                        + "PRIMARY KEY(dayId))");
        create.execute();
    }
    
    /**
     * @return the month
     */
    public int getMonth() {
        return month;
    }

    /**
     * @return the year
     */
    public int getYear() {
        return year;
    }

    /**
     * @return the day
     */
    public int getDay() {
        return day;
    }

    /**
     * @return the date
     */
    public String getDate() {
        return date;
    }
}
